import {
  Action,
  ActionPanel,
  closeMainWindow,
  Detail,
  Icon,
  open,
  PopToRootType,
  showToast,
  Toast,
  useNavigation,
} from "@raycast/api";
import { useCallback, useEffect, useState } from "react";
import { removeTask, updateTask, type Task } from "./storage";
import { getTaskStatus, launchTask, readTaskOutput, stopTask } from "./task-manager";
import { execFile } from "child_process";
import { homedir } from "os";

const EXTENDED_PATH = `${homedir()}/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:${process.env.PATH || ""}`;

async function checkPrOpen(prUrl: string, dir: string): Promise<boolean> {
  return new Promise((resolve) => {
    execFile(
      "gh",
      ["pr", "view", prUrl, "--json", "state"],
      { cwd: dir, encoding: "utf-8", timeout: 10000, env: { ...process.env, PATH: EXTENDED_PATH } },
      (err, stdout) => {
        if (err) { resolve(false); return; }
        try {
          const data = JSON.parse(stdout);
          resolve(data.state?.toLowerCase() === "open");
        } catch {
          resolve(false);
        }
      },
    );
  });
}

const REFRESH_INTERVAL_MS = 1000;
const LATEST_OUTPUT_LINE_LIMIT = 6;
const EMPTY_OUTPUT_TEXT = "(waiting for output...)";
const REVIEW_REPORT_DELIMITER = "!--------!";

export function extractReviewReport(output: string): string | null {
  const startIdx = output.indexOf(REVIEW_REPORT_DELIMITER);
  if (startIdx === -1) return null;
  const contentStart = startIdx + REVIEW_REPORT_DELIMITER.length;
  const endIdx = output.indexOf(REVIEW_REPORT_DELIMITER, contentStart);
  if (endIdx === -1) return null;
  const content = output.slice(contentStart, endIdx).trim();
  return content || null;
}

function getStatusLabel(status: Task["status"]): string {
  switch (status) {
    case "running":
      return "Running";
    case "completed":
      return "Completed";
    case "failed":
      return "Failed";
    case "stopped":
    case "canceled":
      return "Canceled";
  }
}

function escapeCodeFence(text: string): string {
  return text.replace(/```/g, "'''");
}

function getOutputText(output: string): string {
  const trimmedOutput = output.trimEnd();
  return trimmedOutput || EMPTY_OUTPUT_TEXT;
}

function getLatestOutputText(output: string): string {
  const lines = output
    .trimEnd()
    .split(/\r?\n/)
    .filter((line) => line.trim().length > 0);

  if (lines.length === 0) {
    return EMPTY_OUTPUT_TEXT;
  }

  return lines.slice(-LATEST_OUTPUT_LINE_LIMIT).join("\n");
}

function formatDiffBlock(text: string): string {
  return `\`\`\`diff\n${escapeCodeFence(text)}\n\`\`\``;
}

export function extractGitUrl(task: Task, output: string): string | null {
  if (task.command === "create-pr" || task.command === "review-pr") {
    const githubMatch = output.match(
      /https:\/\/github\.com\/[^/]+\/[^/]+\/pull\/[0-9]+/,
    );
    if (githubMatch) {
      return githubMatch[0];
    }

    const gitlabMatch = output.match(
      /https:\/\/gitlab\.com\/[^\s<>")']+\/-\/merge_requests\/[0-9]+/,
    );
    if (gitlabMatch) {
      return gitlabMatch[0];
    }

    const bitbucketMatch = output.match(
      /https:\/\/bitbucket\.org\/[^\s<>")']+\/pull-requests\/[0-9]+/,
    );
    return bitbucketMatch?.[0] ?? null;
  }
  if (task.command === "git-push") {
    // Prefer commit URL generated by the skill's bash script
    const commitMatch = output.match(
      /https:\/\/(github\.com|gitlab\.com)\/[^\s<>")']+\/commit\/[0-9a-f]+/,
    );
    if (commitMatch) {
      return commitMatch[0];
    }

    const bitbucketCommitMatch = output.match(
      /https:\/\/bitbucket\.org\/[^\s<>")']+\/commits\/[0-9a-f]+/,
    );
    if (bitbucketCommitMatch) {
      return bitbucketCommitMatch[0];
    }

    // HTTPS URLs from git hosts
    const gitHostMatch = output.match(
      /https:\/\/(github\.com|gitlab\.com|bitbucket\.org)\/[^\s<>")']+/g,
    );
    if (gitHostMatch) {
      return gitHostMatch[0].replace(/[.,;:)']*$/, "");
    }
    // SSH format: "To github.com:user/repo.git" or "To git@github.com:user/repo.git"
    const sshMatch = output.match(
      /To\s+(?:git@)?(github\.com|gitlab\.com|bitbucket\.org):([^\s]+)/,
    );
    if (sshMatch) {
      const host = sshMatch[1];
      const path = sshMatch[2].replace(/\.git$/, "");
      return `https://${host}/${path}`;
    }
  }
  return null;
}

function formatStatusLine(status: Task["status"]): string {
  const prefix = status === "running" ? "+" : "-";
  return `${prefix} status: ${getStatusLabel(status)}`;
}

function formatMetadataLine(task: Task): string {
  const elapsed = Math.round((Date.now() - task.startTime) / 1000);
  const parts = [`branch: ${task.branch || "unknown"}`];

  if (task.targetBranch) {
    parts.push(`target: ${task.targetBranch}`);
  }

  parts.push(`dir: ${task.dir}`, `elapsed: ${elapsed}s`);

  return parts.join(" | ");
}

function formatTerminalMarkdown(
  task: Task,
  status: Task["status"],
  output: string,
): string {
  const lines = [
    task.label,
    formatStatusLine(status),
    formatMetadataLine(task),
  ];
  const blocks = [formatDiffBlock(lines.join("\n"))];

  if (status === "running") {
    blocks.push(formatDiffBlock(getLatestOutputText(output)));
  }

  blocks.push(formatDiffBlock(getOutputText(output)));

  return blocks.join("\n\n");
}

export function TaskDetail({
  task,
  allowClear = false,
  onRerunReview,
}: {
  task: Task;
  allowClear?: boolean;
  onRerunReview?: () => void;
}) {
  const { pop, push } = useNavigation();
  const [output, setOutput] = useState("");
  const [status, setStatus] = useState<Task["status"]>(task.status);
  const [hasAutoNavigated, setHasAutoNavigated] = useState(false);
  const [prOpen, setPrOpen] = useState(false);

  const refresh = useCallback(async () => {
    const taskWithCurrentStatus = { ...task, status };
    const nextOutput = readTaskOutput(task);
    const nextStatus = getTaskStatus(taskWithCurrentStatus);

    setOutput(nextOutput);

    if (nextStatus !== status) {
      setStatus(nextStatus);
      await updateTask(task.id, { status: nextStatus });

      // Auto-navigate to review report when review-pr task completes
      if (
        !hasAutoNavigated &&
        task.command === "review-pr" &&
        nextStatus === "completed" &&
        task.prUrl
      ) {
        const report = extractReviewReport(nextOutput);
        if (report) {
          setHasAutoNavigated(true);
          push(
            <ReviewReportDetail
              markdown={report}
              gitUrl={task.prUrl}
              navigationTitle={task.label}
              prState="open"
              dirPath={task.dir}
              onReview={onRerunReview}
            />,
          );
        }
      }
    }
  }, [status, task, hasAutoNavigated, push]);

  useEffect(() => {
    void refresh();
    if (status !== "running") return;
    const timer = setInterval(() => void refresh(), REFRESH_INTERVAL_MS);
    return () => clearInterval(timer);
  }, [refresh]);

  const running = status === "running";
  const finished = status === "completed";
  const gitUrl = finished ? extractGitUrl(task, output) : null;

  useEffect(() => {
    if (task.command !== "create-pr" || !gitUrl) {
      setPrOpen(false);
      return;
    }
    void checkPrOpen(gitUrl, task.dir).then(setPrOpen);
  }, [task.command, task.dir, gitUrl]);

  async function handleStop() {
    await showToast({ style: Toast.Style.Animated, title: "Stopping task..." });
    await stopTask({ ...task, status });
    setStatus("stopped");
    setOutput(readTaskOutput(task));
    await showToast({ style: Toast.Style.Success, title: "Task canceled" });
  }

  async function handleClear() {
    await removeTask(task.id);
    pop();
  }

  async function handleCloseMainWindow() {
    await closeMainWindow({
      clearRootSearch: true,
      popToRootType: PopToRootType.Immediate,
    });
  }

  const reviewReport =
    finished && task.command === "review-pr" && task.prUrl
      ? extractReviewReport(output)
      : null;
  const markdown = formatTerminalMarkdown(task, status, output);

  return (
    <Detail
      markdown={markdown}
      navigationTitle={task.label}
      actions={
        <ActionPanel>
          {reviewReport && task.prUrl && (
            <Action
              title="View Review Report"
              icon={Icon.Document}
              onAction={() =>
                push(
                  <ReviewReportDetail
                    markdown={reviewReport}
                    gitUrl={task.prUrl!}
                    navigationTitle={task.label}
                    prState="open"
                    dirPath={task.dir}
                    onReview={onRerunReview}
                  />,
                )
              }
            />
          )}
          {!(reviewReport && task.prUrl) && (
            <Action
              title="Close Raycast"
              icon={Icon.Window}
              onAction={() => void handleCloseMainWindow()}
            />
          )}
          {gitUrl && (
            <>
              <Action.CopyToClipboard
                title="Copy Git Link"
                content={gitUrl}
              />
              <Action
                title="Open Git Link"
                icon={Icon.Link}
                shortcut={{ modifiers: ["cmd"], key: "o" }}
                onAction={() => {
                  void open(gitUrl);
                  void handleCloseMainWindow();
                }}
              />
            </>
          )}
          {reviewReport && task.prUrl && (
            <Action
              title="Close Raycast"
              icon={Icon.Window}
              onAction={() => void handleCloseMainWindow()}
            />
          )}
          {task.command === "create-pr" && prOpen && gitUrl && (
            <Action
              title="Review PR"
              icon={Icon.MagnifyingGlass}
              shortcut={{ modifiers: ["cmd", "shift"], key: "r" }}
              onAction={async () => {
                const toast = await showToast({ style: Toast.Style.Animated, title: "Starting PR review..." });
                try {
                  const reviewTask = await launchTask("review-pr", task.dir, "review-pr", { prUrl: gitUrl });
                  toast.style = Toast.Style.Success;
                  toast.title = "PR review task started";
                  push(
                    <TaskDetail
                      task={reviewTask}
                      onRerunReview={async () => {
                        const t = await launchTask("review-pr", task.dir, "review-pr", { prUrl: gitUrl });
                        push(<TaskDetail task={t} />);
                      }}
                    />,
                  );
                } catch (error) {
                  toast.style = Toast.Style.Failure;
                  toast.title = "Failed to start PR review";
                  toast.message = error instanceof Error ? error.message : String(error);
                }
              }}
            />
          )}
          <Action.CopyToClipboard
            title="Copy Output"
            content={output}
            shortcut={{ modifiers: ["cmd", "shift"], key: "enter" }}
          />
          <Action
            title="Refresh"
            icon={Icon.ArrowClockwise}
            shortcut={{ modifiers: ["cmd"], key: "r" }}
            onAction={() => void refresh()}
          />
          {running && (
            <Action
              title="Stop Task"
              icon={Icon.Stop}
              style={Action.Style.Destructive}
              shortcut={{ modifiers: ["cmd"], key: "." }}
              onAction={() => void handleStop()}
            />
          )}
          {allowClear && !running && (
            <Action
              title="Clear Task & Back"
              icon={Icon.Trash}
              style={Action.Style.Destructive}
              onAction={() => void handleClear()}
            />
          )}
          <Action
            title="Back"
            icon={Icon.ArrowLeft}
            shortcut={{ modifiers: ["cmd"], key: "[" }}
            onAction={pop}
          />
        </ActionPanel>
      }
    />
  );
}

export function ReviewReportDetail({
  markdown,
  gitUrl,
  navigationTitle,
  prState,
  dirPath,
  onReview,
}: {
  markdown: string;
  gitUrl: string;
  navigationTitle: string;
  prState?: string;
  dirPath?: string;
  onReview?: () => void;
}) {
  const { pop } = useNavigation();

  async function handleCloseMainWindow() {
    await closeMainWindow({
      clearRootSearch: true,
      popToRootType: PopToRootType.Immediate,
    });
  }

  const canReview = prState === "open" && dirPath && onReview;

  return (
    <Detail
      markdown={markdown}
      navigationTitle={navigationTitle}
      actions={
        <ActionPanel>
          <Action
            title="Close Raycast"
            icon={Icon.Window}
            onAction={() => void handleCloseMainWindow()}
          />
          <Action.CopyToClipboard
            title="Copy PR Link"
            content={gitUrl}
          />
          <Action
            title="Open in Browser"
            icon={Icon.Globe}
            shortcut={{ modifiers: ["cmd"], key: "o" }}
            onAction={() => {
              void open(gitUrl);
              void handleCloseMainWindow();
            }}
          />
          {canReview && (
            <Action
              title="Re-run Review"
              icon={Icon.ArrowClockwise}
              shortcut={{ modifiers: ["cmd"], key: "r" }}
              onAction={onReview}
            />
          )}
          <Action
            title="Back"
            icon={Icon.ArrowLeft}
            shortcut={{ modifiers: ["cmd"], key: "[" }}
            onAction={pop}
          />
        </ActionPanel>
      }
    />
  );
}
